
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/data/data/com.termux/files/home/.pm2/pm2.log last 15 lines:
PM2        | 2024-07-18T17:26:27: PM2 error: TypeError: One of the pids provided is invalid
PM2        | 2024-07-18T17:26:57: PM2 error: Error caught while calling pidusage
PM2        | 2024-07-18T17:26:57: PM2 error: TypeError: One of the pids provided is invalid
PM2        | 2024-07-18T17:27:27: PM2 error: Error caught while calling pidusage
PM2        | 2024-07-18T17:27:27: PM2 error: TypeError: One of the pids provided is invalid
PM2        | 2024-07-18T17:27:57: PM2 error: Error caught while calling pidusage
PM2        | 2024-07-18T17:27:57: PM2 error: TypeError: One of the pids provided is invalid
PM2        | 2024-07-18T17:28:27: PM2 error: Error caught while calling pidusage
PM2        | 2024-07-18T17:28:27: PM2 error: TypeError: One of the pids provided is invalid
PM2        | 2024-07-18T17:28:57: PM2 error: Error caught while calling pidusage
PM2        | 2024-07-18T17:28:57: PM2 error: TypeError: One of the pids provided is invalid
PM2        | 2024-07-18T17:29:06: PM2 error: Error caught while calling pidusage
PM2        | 2024-07-18T17:29:06: PM2 error: TypeError: One of the pids provided is invalid
PM2        | 2024-07-18T17:29:23: PM2 error: Error caught while calling pidusage
PM2        | 2024-07-18T17:29:23: PM2 error: TypeError: One of the pids provided is invalid

/data/data/com.termux/files/home/.pm2/logs/CAIbot-error.log last 15 lines:
0|CAIbot   |     at ClientRequest.<anonymous> (/data/data/com.termux/files/home/AI-Characters-v2/node_modules/ws/lib/websocket.js:881:5)
0|CAIbot   |     at ClientRequest.emit (node:events:520:28)
0|CAIbot   |     at TLSSocket.socketErrorListener (node:_http_client:502:9) {
0|CAIbot   |   context: {
0|CAIbot   |     error: Error: getaddrinfo ENOTFOUND gateway.discord.gg
0|CAIbot   |         at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
0|CAIbot   |       errno: -3007,
0|CAIbot   |       code: 'ENOTFOUND',
0|CAIbot   |       syscall: 'getaddrinfo',
0|CAIbot   |       hostname: 'gateway.discord.gg'
0|CAIbot   |     }
0|CAIbot   |   }
0|CAIbot   | }
0|CAIbot   | (node:12045) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [WebSocket]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
0|CAIbot   | (Use `node --trace-warnings ...` to show where the warning was created)

/data/data/com.termux/files/home/.pm2/logs/caibot-error.log last 15 lines:
1|caibot   |     at TLSSocket.socketErrorListener (node:_http_client:502:9) {
1|caibot   |   context: {
1|caibot   |     error: Error: getaddrinfo ENOTFOUND gateway-us-east1-b.discord.gg
1|caibot   |         at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
1|caibot   |       errno: -3007,
1|caibot   |       code: 'ENOTFOUND',
1|caibot   |       syscall: 'getaddrinfo',
1|caibot   |       hostname: 'gateway-us-east1-b.discord.gg'
1|caibot   |     }
1|caibot   |   }
1|caibot   | }
1|caibot   | (node:12044) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [WebSocket]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
1|caibot   | (Use `node --trace-warnings ...` to show where the warning was created)
1|caibot   | (node:31254) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [WebSocket]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
1|caibot   | (Use `node --trace-warnings ...` to show where the warning was created)

/data/data/com.termux/files/home/.pm2/logs/CAIbot-out.log last 15 lines:
0|CAIbot   | Executed command: ping
0|CAIbot   | Received command: getLogs
0|CAIbot   | Command not found: getLogs
0|CAIbot   | Received command: getLogs
0|CAIbot   | Command not found: getLogs
0|CAIbot   | Received command: getLogs
0|CAIbot   | Command not found: getLogs
0|CAIbot   | Received command: getLogs
0|CAIbot   | Command not found: getLogs
0|CAIbot   | Received command: getLogs
0|CAIbot   | Command not found: getLogs
0|CAIbot   | Received command: getLogs
0|CAIbot   | Command not found: getLogs
0|CAIbot   | Received command: getLogs
0|CAIbot   | Command not found: getLogs

/data/data/com.termux/files/home/.pm2/logs/caibot-out.log last 15 lines:
1|caibot   |     name: 'removeCharacter',
1|caibot   |     description: 'Remove A CAI Character',
1|caibot   |     execute: [AsyncFunction: execute]
1|caibot   |   },
1|caibot   |   'setCAIAuth' => {
1|caibot   |     name: 'setCAIAuth',
1|caibot   |     description: 'Set The Character AI Auth Token',
1|caibot   |     execute: [Function: execute]
1|caibot   |   }
1|caibot   | }
1|caibot   | Bot is online!
1|caibot   | Logged in to CAINode successfully.
1|caibot   | Connected to character iSSAEYelKLJkLP8xy3PF0q9tFtbeR5YWI-dEqSDZyl8 successfully.
1|caibot   | Response:  I don't think you're doing any testing, you are just annoying me.
1|caibot   | Response sent: I don't think you're doing any testing, you are just annoying me.

PM2      | Error caught while calling pidusage
PM2      | TypeError: One of the pids provided is invalid
PM2      |     at get (/data/data/com.termux/files/usr/lib/node_modules/pm2/node_modules/pidusage/lib/stats.js:78:23)
PM2      |     at pidusage (/data/data/com.termux/files/usr/lib/node_modules/pm2/node_modules/pidusage/index.js:30:5)
PM2      |     at Object.getMonitorData (/data/data/com.termux/files/usr/lib/node_modules/pm2/lib/God/ActionMethods.js:60:5)
PM2      |     at tasks (/data/data/com.termux/files/usr/lib/node_modules/pm2/lib/Worker.js:150:9)
PM2      |     at Domain.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/pm2/lib/Worker.js:193:7)
PM2      |     at Domain.run (node:domain:388:15)
PM2      |     at Timeout.wrappedTasks [as _onTimeout] (/data/data/com.termux/files/usr/lib/node_modules/pm2/lib/Worker.js:192:7)
PM2      |     at listOnTimeout (node:internal/timers:581:17)
PM2      |     at process.processTimers (node:internal/timers:519:7)
2|caibot | Response:  What are you testing? I'm not a machine unless my whole life is a lie and I can be hacked.
2|caibot | Response sent: What are you testing? I'm not a machine unless my whole life is a lie and I can be hacked.
0|CAIbot | Received command: getLogs
0|CAIbot | Command not found: getLogs
2|caibot | Received command: getLogs
2|caibot | Resolved log file path: /data/data/com.termux/files/home/AI-Characters/servers/CAIBot/storage/logs.txt
2|caibot | Log file exists. Sending the file...
